# fly.toml app configuration file generated for 311-checkpoint-2 on 2023-12-26T16:50:01-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "311-checkpoint-2"
primary_region = "dfw"

[build]

[http_service]
  internal_port = 8003
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
